export let defaultRicorsiData = {
  nominativo: "",
  mail: "",
  cf_piva:"",
  telefono: "",
  cap:"",
  città: "",
  numero_ricorso: "",
  numero_protocollo_interno: "",
  ente: "",
  data_ricezione_ricorso: "",
  data_presentazione_ricorso: "",
  indirizzo: "",
  legale_controparte: "",
  pec: "",
  oggetto_ricorso: "",
  anno_imposta: "",
  importo_atto:"",
  email_notification: "",
  esito: "",
  tributo: "",
  tipologia_atto: "",
  informazioni_aggiuntive: "",
}

export let defaultCartolineData = {
  descrizione_mandante: "",
  codice_mandate: "",
  nome_cognome_debitore:"",
  cf_piva_debitore: "",
  ndg: "",
  data_spedizione:"",
  numero_raccomandata: "",
  data_notifica: "",
  esito_notifica: "",
  chiave_pratica: "",
  fase: "",
}

export let defaultFasiData = {
  fase: "",
  contro_deduzioni_tax_unit: "",
  contro_deduzioni_uff_legale:"",
  presentato: "",
  data_presentazione: "",
  data_convocazione:"",
  data_deposito: "",
  sede: "",
  esito: "",
  esito_definitivo: "",
  motivazione: "",
  spese: '',
  data_deposito_sentenza: '',
  data_notifica_sentenza: '',
}