export let formData = {
  nominativo: "",
  mail: "",
  cf_piva:"",
  telefono: "",
  cap:"",
  città: "",
  numero_ricorso: "",
  numero_protocollo_interno: "",
  ente: "",
  data_ricezione_ricorso: "",
  data_presentazione_ricorso: "",
  indirizzo: "",
  legale_controparte: "",
  pec: "",
  oggetto_ricorso: "",
  anno_imposta: "",
  importo_atto:"",
  email_notification: "",
  esito: "",
  tributo: "",
  tipologia_atto: "",
  informazioni_aggiuntive: "",
}