<option value="Ricorso">Ricorso</option>
<option value="Istruttoria">Istruttoria</option>
<option value="DocVaria_Ricorso">Doc Varia Ricorso</option>
<option value="Accertamento">Accertamento</option>
<option value="Note_Tecniche">Note Tecniche</option>
<option value="Controdeduzioni">Controdeduzioni</option>
<option value="Nota_Integrativa">Nota Integrativa</option>
<option value="Dispositivo">Dispositivo</option>
<option value="Appello">Appello</option>
<option value="Controdeduzioni_Appello">Controdeduzioni Appello</option>
<option value="DocVaria_Appello">Doc Varia Appello</option>
<option value="Dispositivo">Dispositivo</option>
<option value="Sentenza_II_Grado">Sentenza II Grado</option>
<option value="Ricorso_Cassazione">Ricorso Cassazione</option>
<option value="16_Controdeduzioni_Cassazione">Controdeduzioni Cassazione</option>
<option value="Dispositivo_Cassazione">Dispositivo Cassazione</option>
<option value="Sentenza_Cassazione">Sentenza Cassazione</option>
<option value="Varie">Varie</option>